language: go

go:
  - 1.8.x

go_import_path: google.golang.org/grpc

before_install:
  - if [[ $TRAVIS_GO_VERSION = 1.8* ]]; then go get -u github.com/golang/lint/golint honnef.co/go/tools/cmd/staticcheck; fi
  - go get -u golang.org/x/tools/cmd/goimports github.com/axw/gocov/gocov github.com/mattn/goveralls golang.org/x/tools/cmd/cover

script:
  - ./benchmark/compare/compare_travis.sh
  - ls
